### PR TITLE
feat: webhook spawn runners

### LINKED ISSUE #1: Switch to webhook-based runner creation
# Problem

Currently it's hard to rerun failed jobs using self-hosted runners because you must first rerun the setup runners job and then run the failed jobs. This is inconvenient, and also can result in wasted AWS costs for runners that are never used in the rerun scenario.

Furthermore the current approach requires special actions code and secrets to be added to the repo.

# Solution

Use GitHub webhooks to spawn runners on-demand. Listen for the job started event, filter for the necessary labels, and use the AWS API to spawn runner tasks directly. Propose to use an AWS Rust lambda, and then allow the service to call the APIs without secrets.

The service would parse out sizing information from the label, making it easy to use self-hosted runners of any size.

- [ ] Test calling AWS API to spawn task from Rust
- [ ] Add GitHub webhook handling via axum & Cloudflare tunnel
- [ ] Test MVP w/ a PR against AppKit & try rerunning a job
- [ ] Put it in an AWS lambda & deploy manually (copy from data-lake-api)
- [ ] Setup IAM role for auto permissions
- [ ] Deploy from CD (copy from data-lake-api)
- [ ] Stretch: Some parsing of the label to set params (e.g. CPU & memory)

### PR DESCRIPTION
**Pull request by chris13524**
Resolves #1 

- [x] Test calling AWS API to spawn task from Rust
- [x] Add GitHub webhook handling via axum & Cloudflare tunnel
- [x] Test MVP w/ a PR against AppKit & try rerunning a job
- [x] Put it in an AWS lambda & deploy manually (copy from data-lake-api)
- [x] Setup IAM role for auto permissions
- [x] ~~Deploy from CD (copy from data-lake-api)~~ won't bother for now
- [x] Stretch: Some parsing of the label to set params (e.g. CPU & memory)
- [x] Update TF variable w/ secret: `webhook_runners_github_webhook_secret`
- [x] Update TF variables: `webhook_runners_github_pat` & `terraform apply`

### CODE REVIEW

**Review by xDarksome — APPROVED** [review]

**Comment by xDarksome** [comment]
Please also remove the terraform code / gh workflow, which are no longer needed.

**Comment by xDarksome** [comment]
The new runners should still use the self-hosted cache server https://github.com/WalletConnect/gh-actions-runners/blob/main/runner/main.tf#L103

**Comment by chris13524** [comment]
> Please also remove the terraform code / gh workflow, which are no longer needed.

I opted to not remove that in this PR to enable a gradual migration to the new approach. It's also possible there are issues with this new approach and we would need to revert

> The new runners should still use the self-hosted cache server https://github.com/WalletConnect/gh-actions-runners/blob/main/runner/main.tf#L103

@xDarksome wdym? Are you just confirming that they will still use the self-hosted cache server or does something need to change?

**Comment by xDarksome** [comment]
> wdym? Are you just confirming that they will still use the self-hosted cache server or does something need to change?

I didn't see any mention of the cache server in the new code, I assumed you forgot to add it.
Is it using the existing task definition? Fine if so.

**Comment by chris13524** [comment]
> Is it using the existing task definition? Fine if so.

Yeah it's using the existing task definition here: https://github.com/WalletConnect/gh-actions-runners/pull/3/files#diff-fc4fdbf4b72270349ec93fac3dd5c4f44652cc5907571708e972bc695b0f7aacR38

**Pull request merged**
